### ISSUE TITLE
tests fail on windows

### ISSUE THREAD

**Issue by tripodsan** [adobe/git-server#113]
using node 10.6.0 on windows produces:

```
  Server Test
Initialized empty Git repository in C:/Users/tripod/AppData/Local/Temp/tmp-7988Nwimiu2a7f4E/owner1/repo1/.git/
The syntax of the command is incorrect.
    1) "before all" hook for "Starts http server on default port"
    2) "after all" hook for "repository info"

  Testing utils.js
    √ case-sensitive path existence


  1 passing (15s)
  2 failing

  1) Server Test
       "before all" hook for "Starts http server on default port":
     ShellJSInternalError: ENOENT: no such file or directory, open 'sub/sub/some_file.txt'
      at Object.openSync (fs.js:443:3)
      at touchFile (node_modules\shelljs\src\touch.js:68:19)
      at C:\Users\tripod\codez\git-server\node_modules\shelljs\src\touch.js:47:5
      at Array.forEach (<anonymous>)
      at Object._touch (node_modules\shelljs\src\touch.js:46:9)
      at Object.touch (node_modules\shelljs\src\common.js:384:25)
      at initRepository (test\server_tests.js:62:9)
      at Context.before (test\server_tests.js:98:11)

  2) Server Test
       "after all" hook for "repository info":
     Error: EBUSY: resource busy or locked, rmdir 'C:\Users\tripod\AppData\Local\Temp\tmp-7988Nwimiu2a7f4E\owner1\repo1'
```

**Comment by trieloff** [comment]
See also https://github.com/isomorphic-git/isomorphic-git/issues/783
